#!/usr/bin/env python3
"""Generate baml_src/tests/yaml-test-suite.generated.baml.

Mirrors the test structure of upstream tests/yaml-test-suite.ts: for each
case file, a testset per case with the applicable checks. PyYAML is only used
to decide *which* checks apply (fail/tree/json/emit presence); the BAML tests
themselves load and parse the case files with the ported library.
"""
import json, os, sys, yaml

ROOT = os.path.expanduser('~/work-repos/yaml-baml-port-src/tests/yaml-test-suite/src')
OUT = os.path.join(os.path.dirname(__file__), '..', 'baml_src', 'tests', 'yaml-test-suite.generated.baml')

skip = {
    '2JQS/0': ['test.event', 'errors'],  # duplicate empty keys are invalid
    '9MMA/0': ['errors'],  # allow stream with directive & no docs
    'SF5V/0': ['errors'],  # allow duplicate %YAML directives
}

def q(s):
    return json.dumps(s, ensure_ascii=False)

lines = ['// GENERATED by tools/gen_yaml_test_suite.py -- do not edit.', '// See yaml-test-suite.baml for the runner functions.', '', 'testset "yaml-test-suite" {']
count = 0
for fn in sorted(os.listdir(ROOT)):
    ident, _, ext = fn.partition('.')
    if ext != 'yaml':
        continue
    with open(os.path.join(ROOT, fn), encoding='utf-8') as f:
        data = yaml.safe_load(f)
    if data[0].get('skip'):
        continue
    name = f"{ident}: {data[0]['name']}"
    for i, case in enumerate(data):
        sd = skip.get(f'{ident}/{i}') or []
        tname = name if len(data) == 1 else f'{name} / {i}'
        lines.append(f'  testset {q(tname)} {{')
        def t(label, fn_):
            global count
            if label in sd:
                lines.append(f'    // skipped upstream: {label}')
                return
            lines.append(f'    test {q(label)} {{ {fn_}({q(ident)}, {i}) }}')
            count += 1
        t('lexer completes', 'yts_lexer')
        t('cst stringify', 'yts_cst')
        fail = case.get('fail', False)
        if not fail and case.get('tree'):
            t('test.event', 'yts_event')
        t('errors', 'yts_errors')
        if not fail:
            if case.get('json'):
                t('in.json', 'yts_in_json')
                t('stringfy+re-parse', 'yts_reparse')
            if case.get('emit'):
                t('out.yaml', 'yts_out_yaml')
        lines.append('  }')
lines.append('}')
with open(OUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f'wrote {count} tests to {OUT}', file=sys.stderr)
