#!/usr/bin/env python3
"""Generate baml_src/tests/json-test-suite.generated.baml.

Mirrors upstream tests/json-test-suite.ts, which enumerates
tests/json-test-suite/{test_parsing,test_transform}/*.json at runtime and
creates one vitest test per file. BAML test blocks are static, so this script
enumerates the files and emits one test per file; each test calls a checker in
json-test-suite.baml that reads the file at test time.
"""
import json, os

ROOT = os.path.expanduser('~/work-repos/yaml-baml-port-src/tests/json-test-suite')
OUT = os.path.join(os.path.dirname(__file__), '..', 'baml_src', 'tests', 'json-test-suite.generated.baml')

# Same skip list as upstream.
skip = {
    'n_structure_100000_opening_arrays': 'Maximum call stack size exceeded',
    'n_structure_open_array_object': 'Maximum call stack size exceeded',
    'y_object_duplicated_key': 'YAMLParseError: Map keys must be unique',
    'y_object_duplicated_key_and_value': 'YAMLParseError: Map keys must be unique',
    'object_same_key_different_values': 'YAMLParseError: Map keys must be unique',
    'object_same_key_same_value': 'YAMLParseError: Map keys must be unique',
    'object_same_key_unclear_values': 'YAMLParseError: Map keys must be unique',
}


def q(s):
    return json.dumps(s, ensure_ascii=False)


lines = [
    '// GENERATED by tools/gen_json_test_suite.py -- do not edit.',
    '// See json-test-suite.baml for the checker functions.',
    '',
    'testset "json-test-suite" {',
]


def emit(sub, fn, checker):
    name = fn[: -len('.json')]
    if name in skip:
        lines.append(f'    test {q(name)} {{ tjts_skipped({q(skip[name])}) }}')
    else:
        lines.append(f'    test {q(name)} {{ {checker}({q(sub + "/" + fn)}) }}')


for describe, sub in [('json-test-suite test_parsing', 'test_parsing'), ('json-test-suite test_transform', 'test_transform')]:
    lines.append(f'  testset {q(describe)} {{')
    for fn in sorted(os.listdir(os.path.join(ROOT, sub))):
        if not fn.endswith('.json'):
            continue
        if sub == 'test_parsing' and not fn.startswith('y_'):
            emit(sub, fn, 'tjts_testReject')
        else:
            emit(sub, fn, 'tjts_testSuccess')
    lines.append('  }')
lines.append('}')
with open(OUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
